---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: agent-daily-briefing-1
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: soma.bhavana.local
    path: "/kube-volumes/agent-daily-briefing-1"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-daily-briefing-1
  namespace: agents
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Mi
  volumeName: agent-daily-briefing-1
