apiVersion: v1
kind: Endpoints
metadata:
  name: mac-bridge
  namespace: agents
subsets:
  - addresses:
      # Update to the IP of the machine running mac-bridge natively
      - ip: 10.0.1.113
    ports:
      - port: 4000
        name: sse
